### ISSUE TITLE
🔧 INFRA-201: Настроить полноценный CI/CD pipeline

### ISSUE THREAD

**Issue by Metatau** [MONO-Digital-Studio/planometrica-studio#14]
## Задача
Создать production-ready CI/CD pipeline для frontend и backend

### 1. Frontend CI (.github/workflows/frontend-ci.yml)
- [ ] Lint (ESLint + Prettier)
- [ ] Type check (TypeScript)
- [ ] Build test
- [ ] Unit tests (Vitest)
- [ ] Bundle size analysis

### 2. Backend CI (.github/workflows/backend-ci.yml)
- [ ] Lint (ESLint + Prettier)
- [ ] Type check (TypeScript)
- [ ] Unit tests (Jest)
- [ ] Integration tests
- [ ] Security audit (npm audit)

### 3. Deploy Staging (.github/workflows/deploy-staging.yml)
- [ ] Deploy frontend to Vercel preview
- [ ] Deploy backend to Railway/Heroku staging
- [ ] Run smoke tests
- [ ] Slack notification

### 4. Deploy Production (.github/workflows/deploy-production.yml)
- [ ] Deploy on git tag (v*)
- [ ] Production environment
- [ ] Database migrations
- [ ] Health checks

## Secrets для настройки
```yaml
VERCEL_TOKEN: <vercel-deployment-token>
RAILWAY_TOKEN: <railway-deployment-token>
DATABASE_URL: <production-db-url>
SLACK_WEBHOOK: <notifications-webhook>
```

## Quality Gates
- [ ] Все тесты должны проходить
- [ ] Code coverage > 80%
- [ ] No high severity vulnerabilities
- [ ] Bundle size < 500KB

## Метрики
- Story Points: 8
- Priority: High
- Type: Infrastructure
- Sprint: 2
- Assignee: VS Code AI
